spring.application.name=Document_chatbot

# .env file se secrets padho (file na mile to error nahi)
spring.config.import=optional:file:.env[.properties]

# Database (values .env se aati hain)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true